### ISSUE TITLE
Four-folded anisotropy description

### ISSUE THREAD

**Issue by kkang14** [SpinW/spinw#46] opened 2020-10-01 01:04 UTC
Dear SpinW team,

Hope you all stay well and healthy.
I want to add the four-folded anisotropy energy, which means that there are two easy axes along with different directions.
So, the magnetic moment can direct any one of those directions.

I am planning to use the approach by combining two different anisotropy matrixes.
For example, if I want to have two easy axes along with x and y directions, I think the combined anisotropy matrix is
Ktot=diag([-a -a 0]) 
which is originated from adding two matrixes, diag([-a 0 0]) and diag([0 -a 0]).

Would you be able to verify I am doing right?
Thank you in advance!

Yours Sincerely,
Kisung Kang

Ph.D. Candidate, Graduate Research Assistant
The Schleife Group
The Department of Materials Science and Engineering
University of Illinois at Urbana-Champaign

**Comment by mducle** [comment] 2021-02-03 11:53
Duplicate of #42

Sorry this is really late...

Unfortunately what I said in #42 is incorrect - adding the two matrices defining two easy-axis directions of equal magnitude effectively just gives you an easy plane anisotropy in the plane defined by the two easy directions - spins with any directions within this plane will have the same energy rather than just the two particular directions you want.

I think there's no way in SpinW to do what you want... I think it probably needs higher order terms than the Si^2 anisotropy terms SpinW uses... and it would be difficult to implement those in the linear spin wave theory SpinW uses...

**Closed** 2021-11-08 10:09 UTC
Labels: question
